[project]
name = "cisco-mcp-server"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "asyncssh>=2.22.0",
    "mcp>=1.26.0",
    "python-dotenv>=1.2.1",
    "scrapli>=2025.1.30",
]
